---
- name: Download theme utility
  ansible.builtin.get_url:
    url: "{{ proxmox_dark_theme_link }}"
    dest: "{{ proxmox_dark_theme_dest }}"
    mode: "{{ proxmox_dark_theme_mode }}"

- name: Run the installer
  ansible.builtin.command: "{{ proxmox_dark_theme_cmd }}"
  register: __theme_install
  changed_when: "'Theme installed' in __theme_install.stdout"
